import { APP_ROUTES } from 'common/constants';

export const ELEMENTS = {
  HOME: {
    ROUTE: APP_ROUTES.HOME,
    STEP: 0,
    NAME: 'Home',
    ID: 'HOME',
  },
  ENTITY_FORM: {
    ROUTE: APP_ROUTES.ENTITY_FORM,
    STEP: 1,
    NAME: 'Entity Form',
    ID: 'ENTITY_FORM',
  },
  ASSOCIATION_FORM: {
    ROUTE: APP_ROUTES.ASSOCIATION_FORM,
    STEP: 2,
    NAME: 'Association Form',
    ID: 'ASSOCIATION_FORM',
  },
  ADMIN_DASHBOARD: {
    ROUTE: APP_ROUTES.ADMIN_DASHBOARD,
    STEP: 3,
    NAME: 'Admin Dashboard',
    ID: 'ADMIN_DASHBOARD',
  },
};

export const ELEMENTS_BY_STEP = {
  [ELEMENTS.ENTITY_FORM.STEP]: ELEMENTS.ENTITY_FORM,
  [ELEMENTS.ASSOCIATION_FORM.STEP]: ELEMENTS.ASSOCIATION_FORM,
  [ELEMENTS.HOME.STEP]: ELEMENTS.HOME,
  [ELEMENTS.ADMIN_DASHBOARD.STEP]: ELEMENTS.ADMIN_DASHBOARD,
};

export const ELEMENTS_BY_NAME = {
  [ELEMENTS.ENTITY_FORM.NAME]: ELEMENTS.ENTITY_FORM,
  [ELEMENTS.ASSOCIATION_FORM.NAME]: ELEMENTS.ASSOCIATION_FORM,
  [ELEMENTS.HOME.NAME]: ELEMENTS.HOME,
  [ELEMENTS.ADMIN_DASHBOARD.NAME]: ELEMENTS.ADMIN_DASHBOARD,
};

export const ELEMENTS_BY_PATH = {
  [APP_ROUTES.HOME]: ELEMENTS.HOME,
  [APP_ROUTES.ENTITY_FORM]: ELEMENTS.ENTITY_FORM,
  [APP_ROUTES.ASSOCIATION_FORM]: ELEMENTS.ASSOCIATION_FORM,
  [APP_ROUTES.ADMIN_DASHBOARD]: ELEMENTS.ADMIN_DASHBOARD,
};
