import { ENTITY_FORM_FIELDS_CONFIG } from '../../../../../Forms/EntityForm/constants';

const columns = [
  {
    title: ENTITY_FORM_FIELDS_CONFIG.ENTITY_NAME.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.ENTITY_NAME.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.ENTITY_NAME.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.SPECIALIZATION.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.SPECIALIZATION.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.SPECIALIZATION.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.PERSON_IN_CHARGE.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.PERSON_IN_CHARGE.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.PERSON_IN_CHARGE.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.GENDER.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.GENDER.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.GENDER.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.NATIONAL_ID_NUMBER.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.NATIONAL_ID_NUMBER.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.NATIONAL_ID_NUMBER.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.OFFICE_TEL_NUMBER.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.OFFICE_TEL_NUMBER.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.OFFICE_TEL_NUMBER.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.EMAIL_ADDRESS.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.EMAIL_ADDRESS.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.EMAIL_ADDRESS.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.SOCIAL_MEDIA.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.SOCIAL_MEDIA.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.SOCIAL_MEDIA.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.ADDRESS.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.ADDRESS.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.ADDRESS.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.CITY.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.CITY.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.CITY.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.PROVINCE.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.PROVINCE.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.PROVINCE.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.NUMBER_OF_NATIONAL_EMPLOYEES.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.NUMBER_OF_NATIONAL_EMPLOYEES.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.NUMBER_OF_NATIONAL_EMPLOYEES.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.NUMBER_OF__NON_NATIONAL_EMPLOYEES.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.NUMBER_OF__NON_NATIONAL_EMPLOYEES.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.NUMBER_OF__NON_NATIONAL_EMPLOYEES.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.STATUS.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.STATUS.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.STATUS.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.VALUE_OF_FUNDING.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.VALUE_OF_FUNDING.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.VALUE_OF_FUNDING.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.NAME_OF_ASSOCIATION.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.NAME_OF_ASSOCIATION.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.NAME_OF_ASSOCIATION.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.PROFILE.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.PROFILE.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.PROFILE.ID,
  },
  {
    title: ENTITY_FORM_FIELDS_CONFIG.ISIC_CLASSIFICATION_NUMBER.LABEL,
    dataIndex: ENTITY_FORM_FIELDS_CONFIG.ISIC_CLASSIFICATION_NUMBER.ID,
    key: ENTITY_FORM_FIELDS_CONFIG.ISIC_CLASSIFICATION_NUMBER.ID,
  },
];

export default columns;
