import { ASSOCIATION_FORM_FIELDS_CONFIG } from '../../../../../Forms/AssociationForm/constants';

const columns = [
  {
    title: ASSOCIATION_FORM_FIELDS_CONFIG.ASSOCIATION_NAME.LABEL,
    dataIndex: ASSOCIATION_FORM_FIELDS_CONFIG.ASSOCIATION_NAME.ID,
    key: ASSOCIATION_FORM_FIELDS_CONFIG.ASSOCIATION_NAME.ID,
  },
  {
    title: ASSOCIATION_FORM_FIELDS_CONFIG.PERSON_IN_CHARGE.LABEL,
    dataIndex: ASSOCIATION_FORM_FIELDS_CONFIG.PERSON_IN_CHARGE.ID,
    key: ASSOCIATION_FORM_FIELDS_CONFIG.PERSON_IN_CHARGE.ID,
  },
  {
    title: ASSOCIATION_FORM_FIELDS_CONFIG.MOBILE_NUMBER.LABEL,
    dataIndex: ASSOCIATION_FORM_FIELDS_CONFIG.MOBILE_NUMBER.ID,
    key: ASSOCIATION_FORM_FIELDS_CONFIG.MOBILE_NUMBER.ID,
  },
  {
    title: ASSOCIATION_FORM_FIELDS_CONFIG.ADDRESS.LABEL,
    dataIndex: ASSOCIATION_FORM_FIELDS_CONFIG.ADDRESS.ID,
    key: ASSOCIATION_FORM_FIELDS_CONFIG.ADDRESS.ID,
  },
  {
    title: ASSOCIATION_FORM_FIELDS_CONFIG.CITY.LABEL,
    dataIndex: ASSOCIATION_FORM_FIELDS_CONFIG.CITY.ID,
    key: ASSOCIATION_FORM_FIELDS_CONFIG.CITY.ID,
  },
  {
    title: ASSOCIATION_FORM_FIELDS_CONFIG.PROVINCE.LABEL,
    dataIndex: ASSOCIATION_FORM_FIELDS_CONFIG.PROVINCE.ID,
    key: ASSOCIATION_FORM_FIELDS_CONFIG.PROVINCE.ID,
  },
  {
    title: ASSOCIATION_FORM_FIELDS_CONFIG.EMAIL.LABEL,
    dataIndex: ASSOCIATION_FORM_FIELDS_CONFIG.EMAIL.ID,
    key: ASSOCIATION_FORM_FIELDS_CONFIG.EMAIL.ID,
  },
  {
    title: ASSOCIATION_FORM_FIELDS_CONFIG.WEBSITE.LABEL,
    dataIndex: ASSOCIATION_FORM_FIELDS_CONFIG.WEBSITE.ID,
    key: ASSOCIATION_FORM_FIELDS_CONFIG.WEBSITE.ID,
  },
];

export default columns;
