export const AUTHENTICATION = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

export const APP = {
  INIT: '@@INIT',
};

export const FORMS = {
  SUBMIT_ENTITY_FORM: 'SUBMIT_ENTITY_FORM',
  SUBMIT_ASSOCIATION_FORM: 'SUBMIT_ASSOCIATION_FORM',
};
