export const AUTHENTICATION = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

export const FORMS = {
  SUBMIT_ENTITY_FORM: 'SUBMIT_ENTITY_FORM',
  SUCCESS_SUBMIT_ENTITY_FORM: 'SUCCESS_SUBMIT_ENTITY_FORM',
  ERROR_SUBMIT_ENTITY_FORM: 'ERROR_SUBMIT_ENTITY_FORM',
  SUBMIT_ASSOCIATION_FORM: 'SUBMIT_ASSOCIATION_FORM',
  SUCCESS_SUBMIT_ASSOCIATION_FORM: 'SUCCES_SUBMIT_ASSOCIATION_FORM',
  ERROR_SUBMIT_ASSOCIATION_FORM: 'ERROR_SUBMIT_ASSOCIATION_FORM',
};

export const REGISTRATION = {
  SUBMIT: 'REGISTRATION/SUBMIT',
  SUCCESS: 'REGISTRATION/SUCCESS',
  ERROR: 'REGISTRATION/ERROR',
};
